require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe QuoteRequestsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Quote. As you add validations to Quote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { number: "Number-1" }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuotesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all quotes as @quotes" do
      get :index, {}, valid_session
    end
  end

  describe "GET #new" do
    it "assigns a new quote as @quote" do
      get :new, {}, valid_session
      expect(assigns(:quote)).to be_a_new(Quote)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Quote" do
        expect {
          post :create, { quote: valid_attributes }, valid_session
        }.to change(Quote, :count).by(1)
      end

      it "assigns a newly created quote as @quote" do
        post :create, { quote: valid_attributes }, valid_session
        expect(assigns(:quote)).to be_a(Quote)
        expect(assigns(:quote)).to be_persisted
      end

      it "redirects to the created quote" do
        post :create, { quote: valid_attributes }, valid_session
        expect(response).to redirect_to(quote_request_path(assigns(:quote).number))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved quote as @quote" do
        post :create, { quote: invalid_attributes }, valid_session
        expect(assigns(:quote)).to be_a_new(Quote)
      end

      it "re-renders the 'new' template" do
        post :create, { quote: invalid_attributes }, valid_session
        expect(response).to render_template("new")
      end
    end
  end

end
